# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before: 
  hooks:
    # Turn this back on when ready to publish a full release version. Can't run tidy while I'm stuck offline so much, because that will clear all unused modules that I will eventually need.
    # - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...


builds:
  - binary: ulldCli
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  mode: keep-existing
  header: |
     ## Ulld release ({{ .Date }})
      
     Checkout the new release!

  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - 
    name: ulldCli
    homepage: https://uhlittlelessdum.com
    commit_author:
      name: Uh-little-less-dum
      email: uhlittlelessdumb@gmail.com


checksum:
  name_template: checksums.txt


changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

announce:
  bluesky:
    enabled: true
    message_template: "The new ULLD cli is out now!"
    username: "uhlittlelessdum.bsky.social"
